export const products = [
  {
    id: 1,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Blue / XL",
    category: "Baju",
    price: 30,
    image: "/images/baju-1.png",
    color: "bg-orange-300",
    isCart: false,
    description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
  },
  {
    id: 2,
    name: "Casual Long Sleeve Plaid Shirt - jiu hong / XXL(65-70KG)",
    category: "Sepatu",
    price: 20,
    image: "/images/sepatu-2.png",
    color: "bg-gray-300",
    isCart: false,
    description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
  },
  {
    id: 3,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
    category: "Baju",
    price: 17,
    image: "/images/baju-3.png",
    color: "bg-red-300",
    isCart: false,
    description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
  },
  {
    id: 4,
    name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
    category: "Celana",
    price: 16,
    image: "/images/celana-4.png",
    color: "bg-yellow-300",
    isCart: false,
    description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
  },
  {
    id: 5,
    name: "Batch Freelancer Men's Button Down Shirt in Aluminum Gray",
    category: "Baju",
    price: 10,
    image: "/images/baju-5.png",
    color: "bg-blue-300",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
  {
    id: 6,
    name: "Men Elegant Shirt And Trouser for office wear mens formal shirt and pants for wedding shirt and pants for groomsmen",
    category: "Baju",
    price: 25,
    image: "/images/baju-6.png",
    color: "bg-pink-300",
    isCart: false,
    description: "Men Elegant Rust Shirt Black Trouser for office wear mens formal shirt and pants for wedding shirt and pants for groomsmen Listing Include ( Pant + Shirt ) Fabric:- TR Imported, Premium Color:- Blue + Gray Dry Clean Only The shirt and pant is for wedding, Party, Proms, and Etc Express Shipping to world-wide but Remote Area May Take Longer Little color variation may possible due to photography and lights WE ARE THE MANUFACTURE AND DESIGNER OF PARTY WEAR SUITS,WEDDING SUITS,GROOM WEAR. WE ALSO ACC",
  },
  {
    id: 7,
    name: "Easy (and Stylish!) Casual Outfit Ideas For Men",
    category: "Celana",
    price: 12,
    image: "/images/celana-1.png",
    color: "bg-gray-300",
    isCart: false,
    description: "How to style shorts in the summer for very hot days and still be stylish . Mens Lifestyle & Fashion inspiration",
  },
  {
    id: 8,
    name: "Men Plaid Print Flap Pocket Coat Without Tee",
    category: "Jam",
    price: 19,
    image: "/images/jam-1.png",
    color: "bg-purple-300",
    isCart: false,
    description: "Free Returns ✓ Free Shipping On Orders $49+ ✓. Men Plaid Print Flap Pocket Coat Without Tee- Men Coats at SHEIN.",
  },
  {
    id: 9,
    name: "Men Flap Pocket Drawstring Hem Cargo Trousers",
    category: "Sepatu",
    price: 14,
    image: "/images/sepatu-1.png",
    color: "bg-yellow-300",
    isCart: false,
    description: "Grey Street Collar Polyester Plain Cargo Pants Embellished Non-Stretch Spring/Summer/Fall Men Bottoms",
  },
  {
    id: 10,
    name: "Voguable New Thin Casual Pants Korea Style Straight Slim Suit Bottoms 3 Colors Classic Fashion Business Leisure Solid Color Trousers",
    category: "Celana",
    price: 14,
    image: "/images/celana-2.png",
    color: "bg-red-300",
    isCart: false,
    description: "Applicable Season: Spring and SummerPant Style: StraightOrigin: CN(Origin)Material: CottonApplicable Scene: DailyStyle: England StyleWaist Type: MIDFront Style: FlatDecoration: PocketsFit Type: RegularGender: MENItem Type: Full LengthThickness: LightweightFabric Type: BroadclothLength: Ankle-Length PantsClosure Type: Zipper Fly",
  },
  {
    id: 11,
    name: "Tooling American Retro Loose Casual Elastic Men's Trousers",
    category: "Celana",
    price: 22,
    image: "/images/celana-3.png",
    color: "bg-emerald-300",
    isCart: false,
    description: "Get ready to experience ultimate comfort and style with our Tooling American Retro Loose Casual Elastic Men's Trousers. These trousers are designed to keep you looking cool and feeling relaxed all day long. The key benefit of these trousers is their exceptional elasticity. With micro elastic fibers, they offer just the right amount of stretch for a comfortable fit without sacrificing style. Say goodbye to restrictive clothing and hello to freedom of movement. Made from a high-quality blend of 97% cotton and 3% polyurethane elastic fiber (spandex), these trousers provide breathability and durability. The cotton fabric ensures excellent comfort and breathability, while the elastic fibers add flexibility and shape retention.",
  },
  {
    id: 12,
    name: "Men's Linen Shirt Button Up Shirt Casual Shirt Summer Shirt Beach Shirt Black White Pink Long Sleeve Plain Lapel Spring Summer Casual Daily Clothing Apparel",
    category: "Jam",
    price: 35,
    image: "/images/jam-2.png",
    color: "bg-blue-300",
    isCart: false,
    description: "Linen, Please refer to the size chart to choose the size that suits you, if you have any questions, please feel free to contact us. This style is suitable for people with a height of 160-190cm/63-74.8in and a person with a weight of 45-95kg/99-209 pounds. If it exceeds 190cm, the shirt may be small. Thank You for visiting our shop! Please contact us if you have any questions. We are here to help with whatever we can:) Men's Cotton Linen Patchwork Shirts, Long Sleeve Washed Cotton",
  },
  {
    id: 13,
    name: "Men's Cotton Linen Patchwork Shirts, Long Sleeve Washed Cotton Linen Shirts, Men's Classic Casual Shirts",
    category: "Sepatu",
    price: 40,
    image: "/images/sepatu-3.png",
    color: "bg-orange-300",
    isCart: false,
    description: "Season:Spring Summer; Fabric:Cotton And Linen; Sleeve Length:Long Sleeve; Look After Me:Wet and Dry Cleaning,Washable; Gender:Men's; Style:Comfortable,Fashion; Tops Type:Summer Shirt,Beach Shirt,Button Up Shirt,Linen Shirt,Casual Shirt; Occasion:Streetwear,Casual,Daily,Holiday,Vacation; Pattern:Plain; Neckline:Lapel; Listing Date:03/28/2023; Bust:; Length:; Shoulder Width:; Fit US Size:null; Fit UK Size:null; Fit EU Size:nul",
  },
  {
    id: 14,
    name: "Camisas para hombre Botón Liso Casual",
    category: "Baju",
    price: 17,
    image: "/images/baju-2.png",
    color: "bg-green-300",
    isCart: false,
    description: "verde menta Casual Collar manga corta Tela Liso Top Embellished No-Elástico",
  },
  {
    id: 15,
    name: "Men Flap Pocket Button Through Corduroy Coat Without Tee",
    category: "Baju",
    price: 30,
    image: "/images/baju-4.png",
    color: "bg-purple-300",
    isCart: false,
    description: "Apricot Casual Long Sleeve Corduroy Plain Other Embellished Non-Stretch Spring/Fall Men Outerwear",
  },
];
